### GENERAL SETTINGS ###

# Site settings
title: Welcome to Go Fly!
description: "Welcome to the Go Fly"
baseurl: "" #important: start with /
url: "http://firstflightgo.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

email: firstflightgo@gmail.com
about: "Go Fly is a flight school launched by Jonathan Rosswog, Matthew O'Gorman, Analyn Bengs, and Eric Lang during the 2015 Rocket City Launch event."
